### ISSUE TITLE
Mislabeled function

### ISSUE THREAD

**Issue by jwcounts** [wnet-ieg-2/pbs-media-manager#1]
Hi! I started experimenting with this plugin for the Houston Public Media/KUHT site, and I noticed a small issue. In the main pbs-media-manager.php file, on line 22, "is_admin" is being read as a constant, but it's a function, so it should be "is_admin()"

Otherwise, good work on getting it set up so far!

**Comment by tamw-wnet** [comment]
Good catch!

**Comment by tamw-wnet** [comment]
Closing, fixed by  e900f5e
